testapp/urls.py
from django.urls import path

from . import views
app_name = 'testapp'

urlpatterns = [
    path('', views.BookList.as_view(), name='employee_list'),
    path('view/<int:pk>', views.BookView.as_view(), name='book_view'),
    path('new', views.BookCreate.as_view(), name='book_new'),
    path('view/<int:pk>', views.BookView.as_view(), name='book_view'),
    path('edit/<int:pk>', views.BookUpdate.as_view(), name='book_edit'),
    path('delete/<int:pk>', views.BookDelete.as_view(), name='book_delete'),
    # path('register/',views.register,name='register'),
    # path('logout/',views.user_login,name='user_login'),

    # path('new', views.EmployeeCreate.as_view(), name='employee_new'),
    # path('delete/<int:pk>', views.EmployeeDelete.as_view(), name='employee_delete'),
    # path('edit/<int:pk>', views.EmployeeUpdate.as_view(), name='employee_edit'),
    # path('', views.EmployeeList.as_view(), name='employee_list'),
    # path('view/<int:pk>', views.EmployeeView.as_view(), name='employee_view'),
]

testcrud/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

from testapp import views

urlpatterns = [
    
    path('employees/', include('testapp.urls')),
    path('admin/', admin.site.urls),
    # path('',views.index,name='index'),
    # path('logout/',views.user_logout,name='logout')
    
]

testapp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.urls import reverse
import datetime

class Employee(models.Model):
    name = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    emailid = models.EmailField()
    department = models.CharField(max_length=200,default='foo')
    doj = models.DateField(default=datetime.date.today)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('book_edit', kwargs={'pk': self.pk})

class EmployeeProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    department = models.CharField(max_length=200,default='foo')
    doj = models.DateField(default=datetime.date.today)
    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('employee_edit', kwargs={'pk': self.pk})

testapp/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from .models import Employee,EmployeeProfileInfo
from django import forms


class DateInput(forms.DateInput):
    input_type = 'date'


class PromiseForm(ModelForm):

    class Meta:
        model = Employee
        fields = ['name', 'password','emailid','department','doj']
        widgets = {
            'doj': DateInput(),
        }
        
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','email','password','first_name','last_name')


class EmployeeProfileInfoForm(forms.ModelForm):
    class Meta():
        model = EmployeeProfileInfo
        
        fields = ('department','doj')
        widgets = {
            'doj': DateInput(),
            
        }

testapp/views.py
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.generic.edit import FormMixin
from testapp.models import Employee,EmployeeProfileInfo
from testapp.forms import PromiseForm, UserForm,EmployeeProfileInfoForm
from django.shortcuts import render


# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
class BookList(ListView):
    model = Employee
    

class BookView(DetailView):
    model = Employee

class BookCreate(CreateView):
    model = Employee
    form_class = PromiseForm
    success_url = reverse_lazy('testapp:employee_list')

class BookUpdate(UpdateView):
    model = Employee
    fields = ['name','emailid','department','doj']
    success_url = reverse_lazy('testapp:employee_list')

class BookDelete(DeleteView):
    model = Employee
    success_url = reverse_lazy('testapp:employee_list')

# Create your views here.
def index(request):
    return render(request,'testapp/index.html')


def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = EmployeeProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'department' in request.POST:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.department = request.POST['department']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = EmployeeProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'testapp/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))
@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")


def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return render(request,'testapp/employee_list.html',{})
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'testapp/login.html', {})


class EmployeeCreate(CreateView):
    model = EmployeeProfileInfo
    form_class = EmployeeProfileInfoForm
    success_url = reverse_lazy('employee_list')

class EmployeeList(ListView):
    model = EmployeeProfileInfo
    

class EmployeeDelete(DeleteView):
    model = EmployeeProfileInfo
    success_url = reverse_lazy('employee_list')


class EmployeeUpdate(UpdateView):
    model = EmployeeProfileInfo
    fields = ['username','first_name','last_name','email','department','doj']
    success_url = reverse_lazy('employee_list')


class EmployeeView(DetailView):
    model = EmployeeProfileInfo

testapp/templates/testapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee</title>

    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    

</head>
<body>
    <nav class="navbar  mynav" role="navigation" id="navbar">
        <div class="container">
            <ul class="nav navbar-nav">

    <a class="navbar-brand mynav" href="{% url 'index' %}">Employee</a>

                
              <li><a href="{% url 'testapp:register' %}" class="btn btn-simple">Register</a></li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a class="navbar-link" href="{% url 'testapp:user_login' %}">Login</a></li>
        {% endif %}
                    
                </ul>

                

        </div>
    </nav>
    <div class="container mycontent">
        {% block content %}

        {% endblock %}

      </div>
      
</body>

</html>

testapp/templates/testapp/employee_confirm_delete.html
<h1>Employee Delete</h1>
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

testapp/templates/testapp/employee_detail.html
<h1>Employee Details</h1>
<h2>Name: {{object.username}}</h2>
Pages: {{ object.password }}

testapp/templates/testapp/employee_form.html
<h1> Employee </h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

testapp/templates/testapp/employee_list.html
<h1>Dashbord and Employee listing Page</h1>
<h2> Employee listing </h2>
<br><br>
<button type="button" ><a href="{% url "testapp:book_new" %}">Add New</a></button>

<br><br>
<table border="1">
<thead>
    <tr>
    <th>Actions</th>
    <th>User ID</th>
    <th>Password</th>
    <th>Email ID</th>
    <th>Department</th>
	<th>Date of joining</th>
    </tr>
</thead>
<tbody>
    {% for book in object_list %}
    <tr>
	
    <td><button type="button" ><a href="{% url "testapp:book_edit" book.id %}">edit</a></button><button type="button" ><a href="{% url "testapp:book_delete" book.id %}">delete</a></button></td>
    
    <td>{{ book.username }}</td>
    <td>{{ book.password }}</td>
    <td>{{ book.emailid }}</td>
	<td>{{ book.department }}</td>
	<td>{{ book.doj }}</td>
    </tr>
    {% endfor %}
</tbody>
</table>
<br>

testapp/templates/testapp/index.html
{% extends "testapp/base.html" %}
{% block content %}
<div class="container"></div>
{% endblock %}

testapp/templates/testapp/login.html
{% extends 'testapp/base.html' %}
{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h1>Please Login</h1>

        <form method="post" action="{% url 'testapp:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password"></label>
          <input type="password" name="password">

          <input type="submit" name="" value="Login">

        </form>

    </div>
  </div>
{% endblock %}

testapp/templates/testapp/registration.html
{% extends "testapp/base.html" %}
}
{% block content %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>

        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>

      {% endif %}

    </div>

  </div>


{% endblock %}